Added check for unnecessary capabilities

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -21,7 +21,7 @@ jobs:
       run: ./docker_setup.sh
 
     - name: Run Trivy Vulnerability scanner
-      uses: aquasecurity/trivy-action@0.20.0
+      uses: aquasecurity/trivy-action@0.28.0
       with:
         image-ref: 'pastebin_app'
         format: 'table'
@@ -83,4 +83,13 @@ jobs:
           exit 1
         else
           echo "User does not have root access"
+        fi
+
+    - name: Check running capabilities (only NET_BIND_SERVICE should be enabled)
+      run: |
+        if [ "$CAPS" != "[NET_BIND_SERVICE]" ]; then
+          echo "Error: Unexpected capabilities enabled. Found: $CAPS."
+          exit 1
+        else
+          echo "Only NET_BIND_SERVICE capabilitiy is enabled."
         fi
